// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiikv91qskZrI7rXTK0n_AQEiCPWjvKws',
    appId: '1:900037950060:web:565d4748c88553b380f649',
    messagingSenderId: '900037950060',
    projectId: 'http-request-6f31d',
    authDomain: 'http-request-6f31d.firebaseapp.com',
    databaseURL: 'https://http-request-6f31d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'http-request-6f31d.appspot.com',
    measurementId: 'G-C7N5N72NBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhsGp1q6dcJZ5s0p3T_253C_SenyP8Bkg',
    appId: '1:900037950060:android:bb5ec942f811b14980f649',
    messagingSenderId: '900037950060',
    projectId: 'http-request-6f31d',
    databaseURL: 'https://http-request-6f31d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'http-request-6f31d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdBGwNIn6NYwOajAjpMIyFVdZwMvC2oPM',
    appId: '1:900037950060:ios:dc2b895473a16b4c80f649',
    messagingSenderId: '900037950060',
    projectId: 'http-request-6f31d',
    databaseURL: 'https://http-request-6f31d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'http-request-6f31d.appspot.com',
    iosBundleId: 'learning-flutter.com.mynotesYt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdBGwNIn6NYwOajAjpMIyFVdZwMvC2oPM',
    appId: '1:900037950060:ios:dc2b895473a16b4c80f649',
    messagingSenderId: '900037950060',
    projectId: 'http-request-6f31d',
    databaseURL: 'https://http-request-6f31d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'http-request-6f31d.appspot.com',
    iosBundleId: 'learning-flutter.com.mynotesYt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_GplaVe9P9L_JNkpj94piJM0fmi44ajI',
    appId: '1:900037950060:web:3f3ad04c7c1e37af80f649',
    messagingSenderId: '900037950060',
    projectId: 'http-request-6f31d',
    authDomain: 'http-request-6f31d.firebaseapp.com',
    databaseURL: 'https://http-request-6f31d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'http-request-6f31d.appspot.com',
    measurementId: 'G-ZPYTRCW6KK',
  );
}
